parameters:
  vmImage: '' # Must be specified in primary YAML
  pythonVersion: ["3.7", "3.8", "3.9", "3.10"]
  resources:
    containers:
    - container: postgres
      image: postgres:11
      ports:
      - 5432:5432
      env:
        POSTGRES_DB: "test_ci"
        POSTGRES_HOST_AUTH_METHOD: "trust"
    - container: mysql
      image: mysql:8.0.20
      ports:
        - 3306:3306
      env:
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        MYSQL_DATABASE: test_ci
    - container: mssql
      image: mcr.microsoft.com/mssql/server:2019-latest
      env:
        ACCEPT_EULA: Y
        MSSQL_SA_PASSWORD: ReallyStrongPwd1234%^&*
        MSSQL_DB: test_ci
        MSSQL_PID: Developer
      ports:
        - 1433:1433

jobs:
  - ${{ each pythonVersion in parameters.pythonVersion }}:
    - job:
      services:
        postgres: ${{ resources.container.postgres }}
      displayName: full${{ pythonVersion }}
      steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: ${{ pythonVersion }}
          displayName: Use Python ${{ pythonVersion }}

        - bash: python -m pip install --upgrade pip==21.3.1
          displayName: 'Update pip'

        - script: |
            pip install --requirement requirements-dev.txt --constraint constraints-dev.txt
            pip install .
          displayName: 'Install dependencies'

        - script: |
            pip install pytest pytest-cov pytest-azurepipelines
            pytest --napoleon-docstrings --junitxml=junit/test-results.xml --cov=. --cov-report=xml --cov-report=html --ignore=tests/cli --ignore=tests/integration/usage_statistics
          displayName: 'pytest'

        - task: PublishTestResults@2
          condition: succeededOrFailed()
          inputs:
            testResultsFiles: '**/test-*.xml'
            testRunTitle: Publish test results for Python ${{ pythonVersion }}

        - task: PublishCodeCoverageResults@1
          inputs:
            codeCoverageTool: Cobertura
            summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
            reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'

    - job:
      displayName: lightweight${{ pythonVersion }}
      steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: ${{ pythonVersion }}
          displayName: Use Python ${{ pythonVersion }}

        - bash: python -m pip install --upgrade pip==21.3.1
          displayName: 'Update pip'

        - script: |
            pip install --requirement requirements-dev-lite.txt --constraint constraints-dev.txt -e .
          displayName: 'Install dependencies'

        - script: |
            pip install pytest pytest-cov pytest-azurepipelines
            pytest --no-spark --no-postgresql --napoleon-docstrings --junitxml=junit/test-results.xml --cov=. --cov-report=xml --cov-report=html --ignore=tests/cli --ignore=tests/integration/usage_statistics
          displayName: 'pytest'

        - task: PublishTestResults@2
          condition: succeededOrFailed()
          inputs:
            testResultsFiles: '**/test-*.xml'
            testRunTitle: Publish test results for Python ${{ pythonVersion }}

        - task: PublishCodeCoverageResults@1
          inputs:
            codeCoverageTool: Cobertura
            summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
            reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'
