version: "3.2"
services:
  postgres_db:
    image: 258143015559.dkr.ecr.us-east-1.amazonaws.com/docker-hub/library/postgres:15.1
    command:
      - postgres
      - "-c"
      - "max_connections=1000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: test_ci
    networks:
      - dbnet
    ports:
      - "5432:5432"

networks:
  dbnet:
    driver: bridge
