# contrib/ specific ruff linter overrides

# root linter settings are defined in the file below
extend = "../pyproject.toml"

extend-ignore = [
    # https://github.com/charliermarsh/ruff#flake8-type-checking-tch
    # this likely to be a high touch set of rules that most contribs
    # don't need to care about. It may disincentivize type-hinting.
    "TCH",
]

[isort]
known-first-party = ["great_expectations", "tests"]
known-third-party = ["dataprofiler", "capitalone_dataprofiler_expectations"]
