language: python
os:
  - linux
python:
  - "2.7"
#  - "3.6"
env:
#  - PANDAS=0.20.3
  - PANDAS=0.21.0
#  - PANDAS=0.23.4
#  - PANDAS=latest
pre-install:
  - pip install -U --only-binary=numpy,scipy numpy scipy
install:
  - if [ "$PANDAS" = "latest" ]; then pip install pandas; else pip install pandas==$PANDAS; fi
  - pip install -r requirements-dev.txt
script:
  - pytest --cov=great_expectations tests/
after_success:
  - coveralls
