# This file is responsible for configuring the `packaging` pipeline (https://dev.azure.com/great-expectations/great_expectations/_build)
#
# The pipeline is run under the following conditions:
#   - On the main branch when a weekly release is being cut
#   - On the develop branch as scheduled by the below cron job
#
#  `packaging` is meant to test the installation and packaging of Great Expectations in a variety of environments.

schedules:
- cron: 0 0 * * *
  displayName: Scheduled Runs
  branches:
    include:
    - develop
    exclude:
    - main
  always: true # As this is run once a day, we always want to run it (regardless of whether or not changes have occurred)

# trigger:
#   branches:
#     include:
#     - pre_pr-*
#     - main
#     exclude:
#     - develop

# The pipeline is run under two primary conditions: if merging into main or as scheduled by the above cron job.
# variables:
#   isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
#   isScheduled: $[and(eq(variables['Build.SourceBranch'], 'refs/heads/develop'), eq(variables['Build.Reason'], 'Schedule'))]
#   GE_USAGE_STATISTICS_URL: "https://qa.stats.greatexpectations.io/great_expectations/v1/usage_statistics"

strategy:
  matrix:
    linux_36:
      imageName: 'ubuntu-latest'
      pythonVersion: '3.6.15'
    mac_36:
      imageName: 'macOS-latest'
      pythonVersion: '3.6.15'
    windows_36:
      imageName: 'windows-latest'
      pythonVersion: '3.6.15'
    linux_37:
      imageName: 'ubuntu-latest'
      pythonVersion: '3.7.12'
    mac_37:
      imageName: 'macOS-latest'
      pythonVersion: '3.7.12'
    windows_37:
      imageName: 'windows-latest'
      pythonVersion: '3.7.12'
    linux_38:
      imageName: 'ubuntu-latest'
      pythonVersion: '3.8.12'
    mac_38:
      imageName: 'macOS-latest'
      pythonVersion: '3.8.12'
    windows_38:
      imageName: 'windows-latest'
      pythonVersion: '3.8.12'
    linux_39:
      imageName: 'ubuntu-latest'
      pythonVersion: '3.9.10'
    mac_39:
      imageName: 'macOS-latest'
      pythonVersion: '3.9.10'
    windows_39:
      imageName: 'windows-latest'
      pythonVersion: '3.9.10'

pool:
  vmImage: $(imageName)

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(pythonVersion)'
    displayName: 'Use Python $(pythonVersion)'

  - bash: python -m pip install --upgrade pip==21.3.1
    displayName: 'Update pip'

  - bash: pip install --requirement requirements-dev-base.txt --constraint constraints-dev.txt
    displayName: 'Install dev requirements'

  - bash: pip install .
    displayName: 'Install core requirements'
