# This file is responsible for configuring the `manual-staging-json-to-prod` pipeline (https://dev.azure.com/great-expectations/great_expectations/_build)
#
# The pipeline is run under the following conditions:
#   - Manually triggered
#
# The sole purpose of this pipeline is to copy staging JSON files to prod for the Expectation Gallery and trigger the prod algolia indices.

trigger:
  - none

stages:
  - stage: deploy_gallery_prod
    pool:
      vmImage: 'ubuntu-22.04'

    jobs:
      - job: fetch_staging_and_upload
        timeoutInMinutes: 300

        steps:
          - task: S3Download@1
            inputs:
              regionName: 'us-east-2'
              awsCredentials: 'aws-ci-great-expectations'
              bucketName: 'superconductive-public'
              targetFolder: '$(Build.SourcesDirectory)/assets/scripts'
              globExpressions: '*.json'
              sourceFolder: 'static/gallery/'

#         - task: S3Download@1
#           inputs:
#             regionName: 'us-east-2'
#             awsCredentials: 'aws-ci-great-expectations'
#             bucketName: 'superconductive-public'
#             targetFolder: '$(Build.SourcesDirectory)/assets/scripts'
#             globExpressions: 'package_manifests--staging.json'
#             sourceFolder: 'static/gallery/'

          - bash: pwd; ls -ltr; mv expectation_library_v2--staging.json expectation_library_v2--tmp.json; mv package_manifests--staging.json package_manifests--tmp.json
            workingDirectory: $(Build.SourcesDirectory)/assets/scripts/
            displayName: 'Rename staging to prod (tmp for now)'

          - task: S3Upload@1
            inputs:
              regionName: 'us-east-2'
              awsCredentials: 'aws-ci-great-expectations'
              bucketName: 'superconductive-public'
              sourceFolder: '$(Build.SourcesDirectory)/assets/scripts'
              globExpressions: '*.json'
              targetFolder: 'static/gallery/'
              filesAcl: 'public-read'

          - task: NodeTool@0
            inputs:
              versionSpec: '16.16'

#         - bash: bash ./trigger_algolia.sh
#           workingDirectory: $(Build.SourcesDirectory)/assets/scripts/
#           displayName: 'Update Algolia indexes from S3'
#           env:
#             # algolia credentials
#             ALGOLIA_ACCOUNT: $(ALGOLIA_ACCOUNT)
#             ALGOLIA_EXPECTATION_INDEX: $(ALGOLIA_EXPECTATION_INDEX)
#             ALGOLIA_PACKAGE_EXPEC_INDEX: $(ALGOLIA_PACKAGE_EXPEC_INDEX)
#             ALGOLIA_PACKAGE_INDEX: $(ALGOLIA_PACKAGE_INDEX)
#             ALGOLIA_WRITE_KEY: $(ALGOLIA_WRITE_KEY)
#             # replica indices from expectations for sorting
#             ALGOLIA_EXPEC_REPLICA_ALPHA_ASC_INDEX: $(ALGOLIA_EXPEC_REPLICA_ALPHA_ASC_INDEX)
#             ALGOLIA_EXPEC_REPLICA_ALPHA_DSC_INDEX: $(ALGOLIA_EXPEC_REPLICA_ALPHA_DSC_INDEX)
#             ALGOLIA_EXPEC_REPLICA_COVERAGE_ASC_INDEX: $(ALGOLIA_EXPEC_REPLICA_COVERAGE_ASC_INDEX)
#             ALGOLIA_EXPEC_REPLICA_COVERAGE_DSC_INDEX: $(ALGOLIA_EXPEC_REPLICA_COVERAGE_DSC_INDEX)
#             ALGOLIA_EXPEC_REPLICA_CREATED_ASC_INDEX: $(ALGOLIA_EXPEC_REPLICA_CREATED_ASC_INDEX)
#             ALGOLIA_EXPEC_REPLICA_CREATED_DSC_INDEX: $(ALGOLIA_EXPEC_REPLICA_CREATED_DSC_INDEX)
#             ALGOLIA_EXPEC_REPLICA_UPDATED_ASC_INDEX: $(ALGOLIA_EXPEC_REPLICA_UPDATED_ASC_INDEX)
#             ALGOLIA_EXPEC_REPLICA_UPDATED_DSC_INDEX: $(ALGOLIA_EXPEC_REPLICA_UPDATED_DSC_INDEX)
#             # replica indices from package expectations for sorting
#             ALGOLIA_PACK_EXPEC_REPLICA_ALPHA_ASC_INDEX: $(ALGOLIA_PACK_EXPEC_REPLICA_ALPHA_ASC_INDEX)
#             ALGOLIA_PACK_EXPEC_REPLICA_ALPHA_DSC_INDEX: $(ALGOLIA_PACK_EXPEC_REPLICA_ALPHA_DSC_INDEX)
#             ALGOLIA_PACK_EXPEC_REPLICA_COVERAGE_ASC_INDEX: $(ALGOLIA_PACK_EXPEC_REPLICA_COVERAGE_ASC_INDEX)
#             ALGOLIA_PACK_EXPEC_REPLICA_COVERAGE_DSC_INDEX: $(ALGOLIA_PACK_EXPEC_REPLICA_COVERAGE_DSC_INDEX)
