# This file is responsible for configuring the `packaging_and_installation` pipeline (https://dev.azure.com/great-expectations/great_expectations/_build)
#
# The pipeline is run under the following conditions:
#   - On the main branch when a weekly release is being cut
#   - On the develop branch as scheduled by the below cron job
#
#  `packaging_and_installation` is meant to test the installation and packaging of Great Expectations in a variety of environments.
#
#  This includes:
#  * Linux, MacOS, and Windows
#  * pip and conda
#  * user and developer workflows

schedules:
- cron: 0 0 * * *
  displayName: Scheduled Runs
  branches:
    include:
    - develop
    exclude:
    - main
  always: true # As this is run once a day, we always want to run it (regardless of whether or not changes have occurred)

# trigger:
#   branches:
#     include:
#     - pre_pr-*
#     - main
#     exclude:
#     - develop

resources:
  containers:
  - container: postgres
    image: postgres:11
    ports:
    - 5432:5432
    env:
      POSTGRES_DB: "test_ci"
      POSTGRES_HOST_AUTH_METHOD: "trust"
  - container: mysql
    image: mysql:8.0.20
    ports:
      - 3306:3306
    env:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: test_ci
  - container: mssql
    image: mcr.microsoft.com/mssql/server:2019-latest
    env:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ReallyStrongPwd1234%^&*
      MSSQL_DB: test_ci
      MSSQL_PID: Developer
    ports:
      - 1433:1433

stages:
  - stage: user_install_linux
    dependsOn: []
    jobs:
      - template: azure/user-install-matrix.yml
        parameters:
          vmImage: "ubuntu-latest"

  - stage: dev_install_linux
    dependsOn: user_install_linux
    jobs:
      - template: azure/dev-install-matrix.yml
        parameters:
          vmImage: "ubuntu-latest"

  - stage: user_install_macOS
    dependsOn: []
    jobs:
      - template: azure/user-install-matrix.yml
        parameters:
          vmImage: "macOS-latest"

  - stage: dev_install_macOS
    dependsOn: user_install_macOS
    jobs:
      - template: azure/dev-install-matrix.yml
        parameters:
          vmImage: "macOS-latest"

  - stage: user_install_windows
    dependsOn: []
    jobs:
      - template: azure/user-install-matrix.yml
        parameters:
          vmImage: "windows-latest"

  - stage: dev_install_windows
    dependsOn: user_install_windows
    jobs:
      - template: azure/dev-install-matrix.yml
        parameters:
          vmImage: "windows-latest"
