# This file is responsible for configuring the `packaging` pipeline (https://dev.azure.com/great-expectations/great_expectations/_build)
#
# The pipeline is run under the following conditions:
#   - On the main branch when a weekly release is being cut
#   - On the develop branch as scheduled by the below cron job
#
#  `packaging` is meant to test the installation and packaging of Great Expectations in a variety of environments.

schedules:
- cron: 0 0 * * *
  displayName: Scheduled Runs
  branches:
    include:
    - develop
    exclude:
    - main
  always: true # As this is run once a day, we always want to run it (regardless of whether or not changes have occurred)

# trigger:
#   branches:
#     include:
#     - pre_pr-*
#     - main
#     exclude:
#     - develop

# The pipeline is run under two primary conditions: if merging into main or as scheduled by the above cron job.
# variables:
#   isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
#   isScheduled: $[and(eq(variables['Build.SourceBranch'], 'refs/heads/develop'), eq(variables['Build.Reason'], 'Schedule'))]
#   GE_USAGE_STATISTICS_URL: "https://qa.stats.greatexpectations.io/great_expectations/v1/usage_statistics"

strategy:
  matrix:
    linux-36-pip:
      imageName: 'ubuntu-latest'
      pythonVersion: '3.6'
      runner: 'pip'
    linux-37-pip:
      imageName: 'ubuntu-latest'
      pythonVersion: '3.7'
      runner: 'pip'
    linux-38-pip:
      imageName: 'ubuntu-latest'
      pythonVersion: '3.8'
      runner: 'pip'
    linux-39-pip:
      imageName: 'ubuntu-latest'
      pythonVersion: '3.9'
      runner: 'pip'
    mac-37-pip:
      imageName: 'macOS-latest'
      pythonVersion: '3.7'
      runner: 'pip'
    mac-38-pip:
      imageName: 'macOS-latest'
      pythonVersion: '3.8'
      runner: 'pip'
    mac-39-pip:
      imageName: 'macOS-latest'
      pythonVersion: '3.9'
      runner: 'pip'
    windows-37-pip:
      imageName-pip: 'windows-latest'
      pythonVersion: '3.7'
      runner: 'pip'
    windows-38-pip:
      imageName-pip: 'windows-latest'
      pythonVersion: '3.8'
      runner: 'pip'
    windows-39-pip:
      imageName: 'windows-latest'
      pythonVersion: '3.9'
      runner: 'pip'
    linux-36-conda:
      imageName: 'ubuntu-latest'
      pythonVersion: '3.6'
      runner: 'conda'
    linux-37-conda:
      imageName: 'ubuntu-latest'
      pythonVersion: '3.7'
      runner: 'conda'
    linux-38-conda:
      imageName: 'ubuntu-latest'
      pythonVersion: '3.8'
      runner: 'conda'
    linux-39-conda:
      imageName: 'ubuntu-latest'
      pythonVersion: '3.9'
      runner: 'conda'
    mac-37-conda:
      imageName: 'macOS-latest'
      pythonVersion: '3.7'
      runner: 'conda'
    mac-38-conda:
      imageName: 'macOS-latest'
      pythonVersion: '3.8'
      runner: 'conda'
    mac-39-conda:
      imageName: 'macOS-latest'
      pythonVersion: '3.9'
      runner: 'conda'
    windows-37-conda:
      imageName-conda: 'windows-latest'
      pythonVersion: '3.7'
      runner: 'conda'
    windows-38-conda:
      imageName-conda: 'windows-latest'
      pythonVersion: '3.8'
      runner: 'conda'
    windows-39-conda:
      imageName: 'windows-latest'
      pythonVersion: '3.9'
      runner: 'conda'

stages:
  pool:
    vmImage: $(imageName)

  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
      displayName: 'Use Python $(pythonVersion)'

    - bash: python -m pip install --upgrade pip==21.3.1
      displayName: 'Update pip'

    - bash: pip install --requirement requirements-dev-base.txt --constraint constraints-dev.txt
      displayName: 'Install dev requirements'

    - bash: pip install .
      displayName: 'Install core requirements'
