# Run for all branches.
trigger:
  branches:
    include:
    - '*'
  paths:
    # Performance benchmarks can be slow, so only run them when certain files are triggered.
    # To force the triggering of a benchmark run, please add a note why the tests should run
    # by modifying tests/performance/pipeline_trigger_notes.md, and this will trigger a run.
    include:
    - tests/performance/

variables:
  python.version: '3.9'

jobs:
- job: bigquery_benchmarks
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: 'Use Python $(python.version)'

    - bash: python -m pip install --upgrade pip
      displayName: 'Update pip'

    - script: |
        pip install -r requirements-dev.txt
        displayName: 'Install dependencies'

    - task: DownloadSecureFile@1
      name: gcp_authkey
      displayName: 'Download Google Service Account'
      inputs:
        secureFile: 'superconductive-service-acct.json'
        retryCount: '2'

    - script: |
        pip install pytest-azurepipelines
        pip freeze > pip-freeze.txt
        pytest -v \
          tests/performance/test_bigquery_benchmarks.py \
          --bigquery --performance-tests \
          --junitxml=junit/test-results.xml \
          --benchmark-json=junit/benchmark.json \
          --no-spark --no-postgresql --napoleon-docstrings \
          --cov=. --cov-report=xml --cov-report=html \
          --ignore=tests/cli --ignore=tests/integration/usage_statistics

      displayName: 'pytest'
      env:
        GOOGLE_APPLICATION_CREDENTIALS: $(gcp_authkey.secureFilePath)
        GE_TEST_BIGQUERY_PROJECT: $(GE_TEST_BIGQUERY_PROJECT)

    - task: PublishTestResults@2
      inputs:
        searchFolder: junit
        testResultsFiles: test-results.xml

    - publish: junit/benchmark.json
      artifact: BenchmarkResult

    # The pip freeze output could be helpful to reproduce performance test results.
    - publish: pip-freeze.txt
      artifact: PipFreeze
