coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

flag_management:
  default_rules: # the rules that will be followed for any flag added, generally
    after_n_builds: 10
    carryforward: false
    statuses:
      - type: project
        target: 80%
        threshold: 2% # We allow the coverage to drop by this percent on a PR
      - type: patch
        target: 90%
  # in general these individual flags should correspond to pytest markers
  # individual_flags: # exceptions to the default rules above, stated flag by flag
  # - name: some_flag
  #   statuses:
  #     - type: project
  #       target: 75%
  #     - type: patch
  #       target: 95%
