parameters:
  vmImage: ["ubuntu-latest", "macOS-latest", "windows-latest"]
  pythonVersion: ["3.7", "3.8", "3.9", "3.10"]

jobs:
  - ${{ each vmImage in parameters.vmImage }}:
    - ${{ each pythonVersion in parameters.pythonVersion }}:
      - job:
        displayName: pip_${{ vmImage }}_${{ pythonVersion }}
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(pythonVersion)'
            displayName: 'Use Python $(pythonVersion)'

          - script: |
              python -m pip install --upgrade pip==21.3.1
              pip install great_expectations
            displayName: 'Install Great Expectations'

          - script: |
              great_expectations --version
              great_expectations -y init --no-usage-stats
            displayName: 'Confirm installation'
