package:
  name: great_expectations
  version: "v0.3.0"

source:
  git_rev: "v0.3.0"
  git_url: https://github.com/great-expectations/great_expectations.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python


about:
  home: https://github.com/great-expectations/great_expectations
  license: Apache-2.0
  license_file: LICENSE