[tool.poetry]
name = "great_expectations"
version = "0.12.9"
description = "Always know what to expect of your data"
authors = ["Great Expectations <team@egreatexpectations.io>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.6"
altair = "^4"
black = "^20.8b1"
Click = "~7.1.2"
importlib-metadata = "^1.7"
ipywidgets = "^7,5"
jinja2 = "^2.10"
jsonpatch = "^1.22"
jsonschema = "^2.5"
mistune = "^0.8.4"
numpy = "^1.14"
pandas = ">=0.23"
pyparsing = "^2.4"
python-dateutil = "~2.8.1"
pytz = ">=2015.6"
requests = ">=2.20,<2.24"
"ruamel.yaml" = ">=0.15.24"
scipy = ">=0.19"
termcolor = "^1.1"
tzlocal = "^1.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
