# docs/ specific ruff linter overrides

# root linter settings are defined in the file below
extend = "../pyproject.toml"

line-length = 88 # NOTE: consider changing this to 100 to match the rest of the project
lint.extend-ignore = [
    # https://docs.astral.sh/ruff/rules/magic-value-comparison/
    "PLR2004", # can be tedious and overly verbose in docs
    "E501", # line-too-long # don't want noqa comments in docs
    "TID251", # this is mostly example code not core code
]

[lint.isort]
known-first-party = ["great_expectations", "tests"]
