version: "3.2"
services:
  server:
    image: 258143015559.dkr.ecr.us-east-1.amazonaws.com/docker-hub/library/yandex/clickhouse-server
    ports:
      - "9000:9000"

    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
