name: Alogolia Indexer

on:
 push:
    branches:
      - develop

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get the content of algolia.json as config
      id: algolia_config
      run: echo "::set-output name=config::$(cat ${{ github.workspace }}/algoliaconfig.json | jq -r tostring)"

    - name: Push indices to Algolia
      uses: signcl/docsearch-scraper-action@master
      env:
        APPLICATION_ID: 'B4HD9FJQCB'
        API_KEY: 'c757cefa085b30df6a039ff59d5d1540'
        CONFIG: ${{ github.workspace }}/algoliaconfig.json
