# https://github.com/marketplace/actions/auto-update
name: autoupdate
on:
  pull_request:
    types:
      - auto_merge_enabled
  push:
    branches:
      - main
      - develop

jobs:
  autoupdate:
    name: autoupdate
    if: contains(github.event.pull_request.labels.*.name, 'core-team') # Must be a core-team PR
    runs-on: ubuntu-20.04
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          PR_FILTER: 'auto_merge' # Should only run on PR's that are approved and ready to merge
