name: changelog-bot
on:
  pull_request:
    types:
      - opened
    branches:
      - develop
jobs:
  create-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment
        uses: jungwinter/comment@v1
        with:
          type: create
          body: "**HOWDY! This is your friendly** :robot: **CHANGELOG bot** :robot:

            ------------------------------------------------------------------------


            Please don't forget to add a clear and succinct description of your change
            under the **Develop** header in `docs/changelog.rst`, if applicable. This will
            help us with the release process.


            :sparkles: **Thank you!** :sparkles:"
          issue_number: ${{github.event.number}}
          token: ${{ secrets.GITHUB_TOKEN }}
