name: ci

on:
  pull_request:
  schedule:
    # https://crontab.guru/every-3-hours
    - cron: "0 */3 * * *"
  workflow_dispatch:  # allows manual triggering with branch picker

jobs:
  ci-does-not-run-on-draft-pull-requests:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == true
    steps:
      - run: echo "CI jobs won't run because this is a draft pull request."

  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: "pip"
          cache-dependency-path: |
            requirements-types.txt
            reqs/requirements-dev-contrib.txt

      - name: Install dependencies
        run: pip install -r requirements-types.txt -r reqs/requirements-dev-contrib.txt

      - run: invoke lint --no-fmt
      - run: invoke fmt --check
      - name: Marker-coverage-check
        run: |
          invoke marker-coverage
      - name: Type-check
        run: |
          invoke type-check --ci --pretty
          invoke type-check --ci --pretty  --check-stub-sources

  docs:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: "pip"
          cache-dependency-path: |
            reqs/requirements-dev-test.txt

      - name: Install dependencies
        run: pip install -r reqs/requirements-dev-test.txt

      # TODO: move to separate job?
      - name: check_repo_root_size
        run: sh ./ci/checks/check_repo_root_size.sh
      - name: Docstring linter
        run: invoke docstrings
      - name: line_number_snippet_checker
        run: python ci/checks/check_no_line_number_snippets.py
      - name: name_tag_snippet_checker
        run: python ci/checks/check_only_name_tag_snippets.py
      - name: public_api_report
        run: invoke public-api

  unit-tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache-dependency-path: |
            reqs/requirements-dev-test.txt
            setup.py

      - name: Install dependencies
        run: pip install -c constraints-dev.txt ".[test, snowflake]"

      - name: Run the unit tests
        run: invoke ci-tests -m "unit" --timeout=1.5 --slowest=8

  cloud-tests:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache-dependency-path: |
            reqs/requirements-dev-test.txt
            setup.py

      - name: Install dependencies
        run: |
          pip install $(grep -E '^(invoke)' reqs/requirements-dev-contrib.txt)
          invoke deps --gx-install -m 'cloud' -r test

      - name: Run the tests
        env:
          GX_CLOUD_BASE_URL: ${{secrets.GX_CLOUD_BASE_URL}}
          GX_CLOUD_ORGANIZATION_ID: ${{secrets.GX_CLOUD_ORGANIZATION_ID}}
          GX_CLOUD_ACCESS_TOKEN: ${{secrets.GX_CLOUD_ACCESS_TOKEN}}
        run: invoke ci-tests 'cloud' --up-services --verbose

  marker-tests:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        markers:
          - big
          - cli
          # This is a required test that has been subsumed by the cloud test above.
          # This is a required test stage however. I'll remove this after the above test goes in.
          - cloud and not e2e
          - filesystem
          - docs
          # Remove next line once the 'clickhouse or ...' line merges and update required test in github to point
          # to this new test.
          - openpyxl or pyarrow or project or sqlite
          - clickhouse or openpyxl or pyarrow or project or sqlite
          #- spark
          - mssql
          - mysql
          - trino
          - postgresql
          # - external_sqldialect # tests being skipped likely due to flagging system
        python-version: ["3.8"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache-dependency-path: |
            reqs/requirements-dev-test.txt
            setup.py

      - name: Install dependencies
        run: |
          pip install $(grep -E '^(invoke)' reqs/requirements-dev-contrib.txt)
          invoke deps --gx-install -m '${{ matrix.markers }}' -r test

      - name: Run the tests
        run: invoke ci-tests '${{ matrix.markers }}' --up-services --verbose

  py38-min-versions:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: "pip"
          cache-dependency-path: |
            reqs/requirements-dev-test.txt
      - name: Install dependencies
        run: pip install . -c ci/constraints-test/py38-min-install.txt -r reqs/requirements-dev-test.txt
      - name: Run the tests
        run: invoke tests --unit

  py39-min-versions:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
          cache-dependency-path: |
            reqs/requirements-dev-test.txt
      - name: Install dependencies
        run: pip install . -c ci/constraints-test/py39-min-install.txt -r reqs/requirements-dev-test.txt
      - name: Run the tests
        run: invoke tests --unit

  py310-min-versions:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: |
            reqs/requirements-dev-test.txt
      - name: Install dependencies
        run: pip install . -c ci/constraints-test/py310-min-install.txt -r reqs/requirements-dev-test.txt
      - name: Run the tests
        run: invoke tests --unit
