name: docstring checker

on:
  pull_request

jobs:
  docstring-checker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run script
      id: docstrings
      run: |
        RESULT=$(python scripts/check_docstring_coverage.py)
        OUTPUT=$(echo $RESULT | tail -n 1)
        echo "::set-output name=result::$OUTPUT"
    - uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: docstrings
        message: |
          ${{ steps.docstrings.outputs.result }}
