name: pypideps

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Update pip
        run: |
          python -m pip install --upgrade pip==21.3.1

      - name: Install GX dependencies
        run: |
          pip install \
            --requirement requirements.txt \
            --requirement requirements-dev.txt \
            --requirement reqs/requirements-dev-test.txt \
            --requirement reqs/requirements-dev-spark.txt \
            --requirement reqs/requirements-dev-sqlalchemy.txt \
            --constraint constraints-dev.txt

      - name: Install pipdeptree
        run: |
          pip install pipdeptree

      - name: Run script
        run: |
          python scripts/pypideptree.py
