name: release
on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  build-n-publish:
    name: Build and publish Python distributions to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Update pip
      run: python -m pip install --upgrade pip
    - name: Install Twine and Wheel, and prepare packaging
      run: |
        pip install twine wheel
        git config --global user.email "team@greatexpectations.io"
        git config --global user.name "Great Expectations"
    - name: Build distribution
      run: |
        python setup.py sdist
        python setup.py bdist_wheel
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{secrets.TEST_PYPI_API_TOKEN}}
        repository-url: https://test.pypi.org/legacy/
